{% set name = "sleap-io" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sleap_io-{{ version }}.tar.gz
  sha256: 2348c5a60efa3e3aa4e01025dade0840b9a06bf87d045190610387c377f25666

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy
    - attrs
    - h5py >=3.8.0
    - pynwb
    - ndx-pose
    - pandas
    - simplejson
    - imageio
    - imageio-ffmpeg
    - av

test:
  imports:
    - sleap_io
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Standalone utilities for working with pose data from SLEAP and other tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niksirbi
